export const INTEREST_OPTIONS = [
  "Running",
  "Hiking",
  "Yoga",
  "Basketball",
  "Soccer",
  "Tennis",
  "Pickleball",
  "Swimming",
  "Cycling",
  "Crocheting",
  "Painting",
  "Photography",
  "Gaming",
  "Roblox",
  "Chess",
  "Reading",
  "Writing",
  "Cooking",
  "Baking",
  "Music",
  "Guitar",
  "Piano",
  "Dancing",
  "Movies",
  "Anime",
  "K-Pop",
  "Volunteering",
  "Coding",
  "Robotics",
  "Skateboarding",
  "Surfing",
  "Rock Climbing",
  "Board Games",
  "Pottery",
  "Gardening",
  "Meditation",
  "Travel",
  "Coffee",
  "Foodie",
  "Thrifting",
];

export function getSharedInterests(a = [], b = []) {
  const setB = new Set(b.map((i) => i.toLowerCase()));
  return a.filter((i) => setB.has(i.toLowerCase()));
}